### ISSUE TITLE
スクリーンショットをESCでキャンセルすると、既存フローティングウィンドウが１つ消えてしまう。

### ISSUE THREAD

**Issue by kawaz** [kentya6/Fuwari#12]
タイトルの通りですが、以下の手順で再現します。

- 適当にキャプチャを行う
- 既存のフローティングウィンドウがある状態で、新規キャプチャ取得を開始
- ESCで新規キャプチャをキャンセルする
- キャプチャが中断されたと同時に、既存のフローティングウィンドウが一つ消えてしまう

消えるのは最後にフォーカスしていたウィンドウのようです。
キャプチャキャンセルでウィンドウ消去されてしまうのはバグと思いますので、ご確認お願いします。

バージョンは v0.3 です。

**Comment by kentya6** [comment]
詳細なレポートありがとうございます。
報告していただいた通りの手順で再現することを確認しました。

これはバグですので、v0.4で修正しますmm

**Comment by kentya6** [comment]
@kawaz 
アップデートが遅くなりましたが、先程v0.4をリリースし本件のバグを修正しました。
ぜひアップデートしてご確認いただければと思います。
