### ISSUE TITLE
キャプチャをESCでキャンセルするとアプリが終了してしまう

### ISSUE THREAD

**Issue by Akira07** [kentya6/Fuwari#16]
macOS Mojaveで利用しています。

Fuwariのキャプチャを起動し、そこでESCを押してキャンセルするとアプリが終了してしまいます。
キャプチャは行えますが、キャンセルするとダメなようです。

アプリを起動し直す必要もあり、また、キャプチャ済みのものがあっても終了してしまうので、困っています。

ご対応お願い出来ますでしょうか。

**Comment by pistatium** [comment]
自分の環境でも発生しました。(MacOS Mojava 10.14.4, Fuwari v0.5.1)

キャプチャ後であれば問題ないのですが、キャプチャのカーソルが出ている時にESC押してしまうと右上のサービスごと終了してしまうようです。

お手すきの際対応していただけたら嬉しいです:bow:

**Comment by kentya6** [comment]
@Akira07 @pistatium 
大変長らくお待たせしました。
v0.6.0で修正しました🙇
[こちら](https://apps.apple.com/jp/app/fuwari/id1187652334?mt=12)から最新版をダウンロードできます。
