### ISSUE TITLE
Skitch起動中にFuwariを起動してキャプチャモードにすると操作不能になる

### ISSUE THREAD

**Issue by mitsugogo** [kentya6/Fuwari#2]
Qiitaの記事拝見させてもらいました！
大変便利で使わせて頂いてます！

1点、使用していたところ下記のような現象に陥って抜けられなくなってしまいました。
SkitchとFuwariのショートカットが同じで、双方のキャプチャモードが起動してしまってEscや強制終了等で逃げられずMacが操作不能に陥ってしまいます。
Fuwariのショートカットキーを変更できれば回避できそうな気がします。

**Comment by kentya6** [comment]
使っていただきありがとうございます！

また、ご不便おかけし申し訳ありません。
v0.3でキーボードショートカットの割り当てをカスタマイズ出来るようにする予定です。
遅くとも来週中には対応します！

**Comment by kentya6** [comment]
[v0.21](https://github.com/kentya6/Fuwari/releases)をリリースし、Escによるキャプチャキャンセルを追加しました。
ショートカットキーの変更は次バージョンで対応するのでもう少々お待ちください！

**Comment by kentya6** [comment]
[バージョン0.3](https://github.com/kentya6/Fuwari/releases)をリリースし、キャプチャ機能のショートカットをカスタマイズできるようになりました！
お待たせしました。ぜひ試してみてください。
