### ISSUE TITLE
Fuwari makes cursor stain on the background.

### ISSUE THREAD

**Issue by illusian** [kentya6/Fuwari#21]
Once launch a fuwari makes a stain looks like cursor on the background. It appears only on the background, not hovering any of the windows.

Fuwari version v0.6.0 from App store running on big sur 11.3.1 latest version.
<img width="446" alt="Screen Shot 2021-05-15 at 2 48 56 PM" src="https://user-images.githubusercontent.com/12790663/118346033-bc0dc500-b58c-11eb-928b-636ffb0efbb4.png">

**Comment by kentya6** [comment]
@illusian 
Thank you for your report.
I will fix this issue in the next version.

**Comment by kentya6** [comment]
@illusian 
Sorry for the delay in fix this issue.
The issue has been fixed in v1.0.0.
Thank you for your report.
