### ISSUE TITLE
[Feature request] Esc to close screenshots

### ISSUE THREAD

**Issue by wadackel** [kentya6/Fuwari#3]
Thank you for awesome app !

I'm happy when can close the take screenshot with `Esc`. (part from `cmd+w`.)
I'm rooting for you :muscle:

---

日本語のIssueも見られましたので, 念のため日本語で追記します.
`cmd+w`とは別に, 可能であれば `Esc` を使ってスクリーンショットを閉じれると嬉しいです 😃 

アプリの方針などもあると思うので, 参考程度に検討していただけると幸いです.

**Comment by kentya6** [comment]
Hi, @tsuyoshiwada.
I'll add close screenshot when `Esc` pressed in v0.2.
The v0.2 will release in this weekend.
Thanks. 👍

**Comment by wadackel** [comment]
Hi @kentya6. Thanks for response !
I'm looking forward to the weekend :)

**Comment by kentya6** [comment]
Hi, @tsuyoshiwada.
[v0.21](https://github.com/kentya6/Fuwari/releases) has been released!
Capture cancellation function with Esc is also included.
Since v0.1 was not configured to automatically update it, please download and install the dmg file again.

**Comment by wadackel** [comment]
Hi @kentya6 .
Thanks! confirmed that `v0.21` !

It seems to be working perfectly :smiley:
and other bugs have been fixed, I'm very happy!
