### ISSUE TITLE
デュアルモニタ環境で片方の画面でのキャプチャが出来ない

### ISSUE THREAD

**Issue by dono** [kentya6/Fuwari#4]
環境 : macOS sierra 10.12.1

Qiitaで拝見して使わせて頂いています。

題の通りの事象を観測しました。再起動をしても同じ事象が見られました。

**Comment by kentya6** [comment]
報告ありがとうございます。
申し訳ありませんが、現在リリースしているv0.1ではまだマルチディスプレイ対応ができておりません。
今週末までにリリースするv0.2で対応予定です。もう少々お待ちください。

**Comment by kentya6** [comment]
[v0.21](https://github.com/kentya6/Fuwari/releases)をリリースしました！
マルチディスプレイに対応しました。
v0.1のみ自動アップデートがかからない構成にしてしまっていたので、お手数ですが再度dmgファイルをダウンロードしてインストールしてください。

**Comment by kawaz** [comment]
マルチモニタで使ってみたのですが、確かにどちらのモニタでもキャプチャ出来るのですが、キャプチャ後のウィンドウ位置がおかしいようです。操作動画を撮ってみたので見て頂けると分かりやすいかと。

[![](http://img.youtube.com/vi/lDQprHbtGcM/0.jpg)](https://www.youtube.com/watch?v=lDQprHbtGcM)

上側のモニタでは普通に使えますが、下のモニタでキャプチャすると上画面にウィンドウが出てしまいます。
なお、上モニタに表示されたキャプチャウィンドウを下モニタにドラッグで移動するなどは問題なく動作します。初期位置だけがおかしい感じです。

**Comment by kawaz** [comment]
もう一点おかしな点がありました。キャプチャ開始時に表示されるポインタがマルチディスプレイだと2箇所表示されます。
![img_2091](https://cloud.githubusercontent.com/assets/156236/21475544/43cbceee-cb70-11e6-8bde-c1f60bbe0dce.JPG)

添付画像は下モニタのカーソルが本物なのですが、上モニタにもキャプチャ用ポインタが表示されています。なお上モニタに表示されたポインタはカーソルを動かしても動かず画面上の静止画像みたいな感じで残ったままで、キャプチャを完了orキャンセルすると消えます。

**Comment by kawaz** [comment]
キャプチャ後のウィンドウ位置と、ポインタマークが別モニタに出る問題、ともに v0.3 で修正されていることを確認しました！
