### ISSUE TITLE
起動中に他のアプリケーションで環境設定を開こうとするとFuwariの環境設定が開く

### ISSUE THREAD

**Issue by ug23** [kentya6/Fuwari#5]
Fuwari起動中、他のアプリケーションで環境設定用のショートカット(Command+,)が効かなくなり、代わりにどのアプリケーション上でもFuwariの環境設定が開きます。

Fuwariの環境設定は非アクティブ状態で開くため、ユーザからは Command+,が効かなくなったように見えますが、ウィンドウの陰で環境設定が開いています。

Fuwariを終了させれば他のアプリケーションでCommand+,が効くようになります。

環境は OS X El Capitan 10.11.6 です。

**Comment by kentya6** [comment]
ご報告ありがとうございます。
環境設定のショートカットについても、スクリーンショットと同様にグローバルなショートカットとして登録してしまっていたようです。
v0.2で修正します。 👍

**Comment by kentya6** [comment]
[v0.21](https://github.com/kentya6/Fuwari/releases)をリリースしました！
ご報告頂いた今回の問題を修正したものとなっています。
v0.1のみ自動アップデートがかからない構成にしてしまっていたので、お手数ですが再度dmgファイルをダウンロードしてインストールしてください。

**Comment by ug23** [comment]
試してみて Command+, でFuwariの環境設定が開かず、使用中のAppの環境設定が開くようになっていたので修正されていました！ありがとうございます！
