### ISSUE TITLE
CPU負荷が高い

### ISSUE THREAD

**Issue by kawaz** [kentya6/Fuwari#8]
Fuwariを起動しただけで一度もスクリーンショットを取得したことがない状態では1%以下のCPU使用率ですが、スクリーンショットを一度でも取得すると常に10%〜70%くらいのCPUを消費し続けるようになります。しかも一度その状態になると `esc` で全てのキャプチャウィンドウを閉じてアイコンとして常駐してるだけの状態に戻してもCPU使用率は下がらず、延々と10％〜70%くらいのCPUを消費し続けています。

環境は以下のとおりです。

- MacbookPro 13 (Late 2016, CPUメモリ全部盛りスペック) 
- macOS Siera 10.12.2
- Fuwari 0.21

**Comment by kentya6** [comment]
ご報告ありがとうございます。
こちらで複数キャプチャや`esc`でキャンセルした状態のCPU使用率を見たのですが、再現しませんでした。。（キャプチャ終了させるとCPU負荷が下がります）
ただ、キャプチャ時にCPU負荷が60%程度と高いのは確認しました。
これは他のアプリでのスクショ撮影時も同様の負荷がかかっているのですが、もう少し負荷を軽減できそうな見込みがたったので、次のバージョンリリース時に負荷が軽減されたか、再度確認をお願いできると嬉しいです。

**Comment by ghost** [comment]
同じ現象かは分からないのですが、キャプチャ後に別のスペースに切り替えると高いCPU使用率になっている問題はありました。（カーソルを動かすと負荷が高くなる）
https://github.com/heqate/Fuwari/commit/04a8a53ff417254836e6107de8de9a4cb341dd0d の変更で問題はなくなりましたが、もともとの処理の意図は理解していないです。

**Comment by kawaz** [comment]
キャプチャ時にCPU負荷が高いのはあまり気にしていません。キャプチャ中以外の時にも負荷が高いのが何でだろうと思った次第です。

@heqate さんの修正を試してみようかと、初めてXCodeプロジェクトのビルドをやってみたのですが特に症状は変わりませんでした。僕はフルスクリーンやスペース機能は殆ど使わないので関係ないのかもしれません。

ただし、カーソルを動かすと負荷が高くなるという点が気になったので、アクティビティモニタを見ながらタッチパッドから手を離してみたところピタリとCPU負荷が0%近くになりました。でまたカーソルをグリグリ動かすとCPUが上ることが確認できました。
CPUがどれくらい上がるかは安定せずせいぜい15％くらいしか行かないときもあれば130％とか行くときもあります。特に高い負荷の発生条件はよくわかりませんが、10％台までならマウスぐりぐりしてるだけで簡単に再現します。

内部実装とかは全く見てないのですが、キャプチャ中だけ行えば良いイベントトラッキングを解除し忘れてるとかそんな感じですかね？

**Comment by kentya6** [comment]
@heqate さん、ご意見ありがとうございます。
また、キャプチャ精度の向上なども行っていただき、ありがとうございます。参考にさせていただきます！
@kawaz さん、不要なイベントトラッキングの削除漏れも原因の一つでした。次のバージョンで修正いたします。

**Comment by kentya6** [comment]
[バージョン0.3](https://github.com/kentya6/Fuwari/releases)をリリースしました！
不要なイベントトラッキングも削除したので、不具合修正できていると思います。
今回のバージョンは @heqate さんの修正をいくつか反映しています。ありがとうございましたmm

**Comment by ghost** [comment]
@kentya6 
ありがとうございます！Kiritoriを愛用していたので非常に助かってます:+1:

**Comment by kentya6** [comment]
1時間前のdmgではFuwariの起動に失敗する致命的なバグがあったので、急遽そのバグを修正したdmgを同じバージョン0.3で再アップしました。
もし既にダウンロードしていてこの不具合に遭遇した場合は、最新のdmgファイルをダウンロードしてみてくださいmm

**Comment by kawaz** [comment]
年末で確認が遅くなりましたが、v0.3 でキャプチャ終了後のCPU負荷が上がらなくなったことを確認しました！これで安心して常用できます。

**Comment by kentya6** [comment]
ご確認ありがとうございます！
