### ISSUE TITLE
アプリ起動時にウィンドウ表示しないで欲しい

### ISSUE THREAD

**Issue by kawaz** [kentya6/Fuwari#9]
最初の起動時常に「ショートカット/環境設定/終了」のボタンだけがある小さいウィンドウが表示されますが、このウィンドウを開かず起動したいです。

**Comment by kentya6** [comment]
ご報告ありがとうございます。
こちらはいくつか要望を頂いていて、私自身も不要だなと思っているので、次のバージョンで対応します！
もう少々お待ちください。

**Comment by kentya6** [comment]
[バージョン0.3](https://github.com/kentya6/Fuwari/releases)で起動時の画面を削除し、対応しました 👍

**Comment by kawaz** [comment]
確認しました。ありがとうございます！
